### ISSUE TITLE
Comment on rate limit for each visitor

### ISSUE THREAD

**Issue by heldersepu** [HouzuoGuo/Terraform-S3-CDN-exercise#1]
```
// prod_rate_limit imposes a 100 requests/minute rate limit for each visitor.
resource "aws_waf_rate_based_rule" "prod_rate_limit" {
  name        = "prod_rate_limit"
  metric_name = "ProdRateLimit"
  rate_key    = "IP"
  rate_limit  = 100
}
```
https://github.com/HouzuoGuo/Terraform-S3-CDN-exercise/blob/master/app/waf.tf#L12

According to the documentation:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/waf_rate_based_rule#rate_limit

The rate_limit is the maximum number of requests, allowed in a five-minute period. 
`rate_limit  = 100` is a 20 requests/minute rate

**Comment by HouzuoGuo** [comment]
Thank you.

This is now fixe in bbeadf355ff5e35205965baf6272aa09cf09dc8b and 563fd2622f3dde4a0f22ad74f07d7aae278fe64c.
